unbind r
bind r source-file ~/.tmux.conf
set -g history-limit 10000
set -g mouse on
set -g prefix C-s
set -g base-index 1
setw -g pane-base-index 1 # start window numbering at 1
setw -g mode-keys vi
unbind-key -T copy-mode-vi MouseDragEnd1Pane
bind-key -T copy-mode-vi y send-keys -X copy-selection

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'


########### Catppuccin config ###########
set -g @plugin 'catppuccin/tmux#v2.1.2'
# ~/.tmux.conf

# Options to make tmux more pleasant
set -g default-terminal "tmux-256color"
set-option -g status-position top

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run ~/.tmux/plugins/tmux/catppuccin.tmux

## Window global/default configuration
# set -g @catppuccin_window_default_text " #{window_name}"
set -g @catppuccin_window_text "#W" # Essential to keep window name
set -g @catppuccin_window_default_text "#W" # Essential to keep window name
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_number_position "left"

## Window current configuration
# set -g @catppuccin_window_current_text "#{window_name}"
set -g @catppuccin_window_current_text "#W" # Essential to keep window name
set -g @catppuccin_window_current_fill "all"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

# Status
set -gF  status-right "#{@catppuccin_status_directory}"
set -agF status-right "#{@catppuccin_status_session}"
set -agF status-right "#{@catppuccin_status_user}"
set -agF status-right "#{@catppuccin_status_host}"
#########################################


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
